---
title: "Compile_weekly_data"
author: "Jessica McCordic"
date: "2025-09-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load lib}

library(tidyverse)
library(tcltk2)
library(svDialogs)

```



```{r load data}

# Assign user-defined inputs ----------------------------------------------
# 
# # Since server folders are in a standard structure, use parent folder to get list of all deployments
# dep_names <- list.dirs(tk_choose.dir(caption = "Select parent dir for all deployment folders"), recursive = FALSE, full.names = FALSE)
# 
# # select the deployment(s) to summarize
# dep_list <- dlg_list(title = "Select deployments to plot", choices = dep_names, multiple = TRUE)$res |>
#   str_sub(start = 16)


# Manually list deployment names
dep_list <- as.list(c("PARKSAUSTRALIA_CGMP_201807_CG", "PARKSAUSTRALIA_CGMP_201812_CG", "PARKSAUSTRALIA_CGMP_201904_CG",
              "PARKSAUSTRALIA_DAMPIER_202009_DNE", 
              "PARKSAUSTRALIA_MURAT_202002_MRE",
              "PARKSAUSTRALIA_NINGALOO_201909_NGN",
              "PARKSAUSTRALIA_SIMP_201808_WP", "PARKSAUSTRALIA_SIMP_201812_WP", "PARKSAUSTRALIA_SIMP_201906_WP", 
              "PARKSAUSTRALIA_SWC_202201_SWS")|>
  str_sub(start = 16))

# set deployment names
dep_info <- dep_list |>
  set_names(dep_list)


# Load data ---------------------------------------------------------------

# For each deployment in the list, load in UTC hourly presence sheet formatted for HMD join
hp_og <- dep_info |>
  map(~read_csv(choose.files(caption = paste0({.}, " Hourly Presence sheet .csv"))))|>
  # use imap() to get info based on index of each iteration
  # in this case, we want the name of the list element, designated as ".y"
  imap(~mutate(., Dep_ID = .y))


dir_weather <- tk_choose.dir(caption = "Select folder with weather tables (csv)")
weather_og <- dir_weather |>
    # list all files with .txt extension
    list.files(pattern = ".csv") |>
    map_chr(~paste0(dir_weather,"\\",  .)) |>
    # use map to iterate read.delim() function over each file in the directory
    map(~read_csv(.)) 


# load in hourly shrimp presence based on 10kHz TOL band
tol_shrimp <- read_csv("data/All_sites_tables/TOL10khz_shrimp.csv") 

```


```{r reshape and merge hp data}

# making new_cols placeholders to add into original df if they don't exist
new_cols <- c("bal_pres" = 0 , "hbw_pres" = 0 , "fish_c_pres" = 0, 
              "dol_pres" = 0 , "mnk_pres" = 0, 
              "spwh_pres" = 0, "ves_pres" = 0)
hp_allcols <- hp_og |>
  # add columns if they don't exist
  map(~add_column(., !!!new_cols[!names(new_cols) %in% names(.)])
  ) |>
  bind_rows() |>
  left_join(tol_shrimp, by = c("Dep_ID","UTC"))

```

```{r reshape and merge weather}

weather_data <- weather_og |>
  bind_rows() |>
  rename(Dep_ID = "Dep") |>
  # replace missing values coded as -9999 with NA
  mutate(across(-c(UTC, Dep_ID, month_name, tide_station), ~ifelse(. < 0, NA, .)))

hp_env <- hp_allcols |>
  left_join(weather_data, by = c("Dep_ID","UTC"))

```


```{r monthly presence}

hp_month_prop <- hp_env |>
  mutate(month_UTC = month(UTC),
         date_UTC = date(UTC),
         # replace all NA's with 0's in presence cols
         across(ends_with("_pres"), ~replace_na(., 0)),
         # code presence absence as 1/0
         across(ends_with("_pres"), ~if_else(. > 0, 1, 0))) |>
  # group to month level
  group_by(Dep_ID, month_UTC) |>
  summarise(n_days = n_distinct(date_UTC),
            n_hours = n(),
            # caculate total counts per source by month
            bal_count = sum(bal_pres),
            hbw_count = sum(hbw_pres), 
            fish_c_count = sum(fish_c_pres),
            dol_count = sum(dol_pres),
            ves_count = sum(ves_pres),
            mnk_count = sum(mnk_pres),
            spwh_count = sum(spwh_pres),
            shr_count = sum(shr_pres),
            # calculate prop hours present per source per month
            bal_pres = sum(bal_pres)/n_hours,
            hbw_pres = sum(hbw_pres)/n_hours, 
            fish_c_pres = sum(fish_c_pres)/n_hours,
            dol_pres = sum(dol_pres)/n_hours,
            ves_pres = sum(ves_pres)/n_hours,
            mnk_pres = sum(mnk_pres)/n_hours,
            spwh_pres = sum(spwh_pres)/n_hours,
            shr_pres = sum(shr_pres)/n_hours,
            tidal_mag_m = max(height_m, na.rm = TRUE) - min(height_m, na.rm = TRUE),
            mean_water_temp_C = mean(water_temp_C, na.rm = TRUE),
            mean_wind_m_sec = mean(wind_m_sec, na.rm = TRUE),
            mean_wind_km_h = mean(wind_km_h, na.rm = TRUE),
            rain_month_avg_mm = mean(rain_month_avg_mm, na.rm = TRUE),
            wind_am_month_avg_kmh = mean(wind_am_month_avg_kmh, na.rm = TRUE),
            wind_pm_month_avg_kmh = mean(wind_pm_month_avg_kmh, na.rm = TRUE)
            
    ) |>
  filter(n_days >= 0.5*days_in_month(month_UTC)) # only keep months with 15+ days

```


```{r presence by month and light regime}



hp_allcols_light <- hp_env |>
  # add columns for grouping
  mutate(month_UTC = month(UTC),
         date_UTC = date(UTC),
         # replace all NA's with 0's in presence cols
         across(ends_with("_pres"), ~replace_na(., 0)),
         # code presence absence as 1/0
         across(ends_with("_pres"), ~if_else(. > 0, 1, 0))) |>
  
  # get light regime labels
  # get sun elevation by lat/lon
  
  # add in lat/lon by site
  mutate(
    Lat_DD = case_when(
      grepl("_CG",Dep_ID) ~ -31.681,
      grepl("_DNE",Dep_ID) ~ -20.329,
      grepl("_MRE",Dep_ID) ~ -32.584,
      grepl("_NGN",Dep_ID) ~ -22.705,
      grepl("_WP",Dep_ID) ~ -29.698,
      grepl("_SWS",Dep_ID) ~ -33.675,
      grepl("_TRW",Dep_ID) ~ -31.711
    ),
    Lon_DD = case_when(
      grepl("_CG",Dep_ID) ~ 152.91,
      grepl("_DNE",Dep_ID) ~ 117.09,
      grepl("_MRE",Dep_ID) ~ 132.63,
      grepl("_NGN",Dep_ID) ~ 113.55,
      grepl("_WP",Dep_ID) ~ 153.40,
      grepl("_SWS",Dep_ID) ~ 114.58,
      grepl("_TRW",Dep_ID) ~ 115.58
    )
  ) |>
  
  rowwise() |> 
  # assign categories based on sun elev
  mutate(sun_elev_rad = suncalc::getSunlightPosition(UTC, 
                                                     Lat_DD,
                                                     Lon_DD,
                                                     keep = "altitude")$altitude,
         sun_elev_deg = (sun_elev_rad*180)/(pi),
         light_reg = case_when(
           # if sun elev is positive, daytime
           sun_elev_deg > 0 ~ "day",
           # if sun elevation is less than -12, nighttime
           sun_elev_deg < -12 ~ "night",
           # if between 0 and -12, "twilight"
           sun_elev_deg <= 0 & sun_elev_deg >= -12 ~ "twilight"
         )
  ) 
  
hp_monthlight_prop <- hp_allcols_light |>
  # group by month + light regime 
  group_by(Dep_ID, month_UTC, light_reg) |>
  summarise(n_days = n_distinct(date_UTC),
            n_hours = n(),
            # caculate total counts per source
            bal_count = sum(bal_pres),
            hbw_count = sum(hbw_pres), 
            fish_c_count = sum(fish_c_pres),
            dol_count = sum(dol_pres),
            ves_count = sum(ves_pres),
            mnk_count = sum(mnk_pres),
            spwh_count = sum(spwh_pres),
            shr_count = sum(shr_pres),
            # calculate prop hours present per source
            bal_pres = sum(bal_pres)/n_hours,
            hbw_pres = sum(hbw_pres)/n_hours, 
            fish_c_pres = sum(fish_c_pres)/n_hours,
            dol_pres = sum(dol_pres)/n_hours,
            ves_pres = sum(ves_pres)/n_hours,
            mnk_pres = sum(mnk_pres)/n_hours,
            spwh_pres = sum(spwh_pres)/n_hours,
            shr_pres = sum(shr_pres)/n_hours,
            tidal_mag_m = max(height_m, na.rm = TRUE) - min(height_m, na.rm = TRUE),
            mean_water_temp_C = mean(water_temp_C, na.rm = TRUE),
            mean_wind_m_sec = mean(wind_m_sec, na.rm = TRUE),
            mean_wind_km_h = mean(wind_km_h, na.rm = TRUE),
            rain_month_avg_mm = mean(rain_month_avg_mm, na.rm = TRUE),
            wind_am_month_avg_kmh = mean(wind_am_month_avg_kmh, na.rm = TRUE),
            wind_pm_month_avg_kmh = mean(wind_pm_month_avg_kmh, na.rm = TRUE)
    ) |>
  filter(n_days >= 0.5*days_in_month(month_UTC)) # only keep months with 15+ days

```

```{r daily presence plot}

library(PAMscapes)

months_to_use <- hp_allcols_light |>
  group_by(Dep_ID, month_UTC) |>
  summarize(n_days = n_distinct(date_UTC)) |>
  filter(n_days >= 0.5*days_in_month(month_UTC)) |>
  ungroup()

#reshape to long format for plotting
hp_scene <- hp_allcols_light |>
  pivot_longer(all_of(ends_with("_pres")), names_to = "bio_type", values_to = "presence") |>
  # join with months_to_use
  left_join(months_to_use) |>
  # remove NA's from n_days column (i.e., not found in months_to_use)
  filter(!is.na(n_days))|>
  # only include presence so that absence = blank in plot
  filter(presence > 0) |>
  # add columns for individual components for easier plotting
   mutate(hour_start = hour(UTC),
         day_start = date(UTC),
         )

# get df from plotAcousticScene() to put into more flexible ggplot
hp_scene_day <- plotAcousticScene(hp_scene, 
                                  typeCol = "bio_type", 
                                  combineYears = TRUE, 
                                  by = "npz_id", 
                                  bin = "1day", 
                                  fill = TRUE, 
                                  returnData = TRUE) |>
  mutate(month_start = month(UTC),
         month_end = month(end))

hp_scene_hour <- plotAcousticScene(hp_scene, typeCol = "bio_type", combineYears = TRUE, by = "npz_id", bin = "1hour", fill = TRUE, alpha = 0.7, returnData = TRUE) |>
  mutate(hour_start = hour(UTC),
         hour_end = hour(end),
         day_start = date(UTC),
         day_end = date(end))


# create table of data gaps within nominal year (2019)

gaps <- data.frame("Gap_start" = c(as.POSIXct("2019-02-20",format="%Y-%m-%d"), #CGMP gap 1 start
                                   as.POSIXct("2019-08-01",format="%Y-%m-%d"), #CGMP gap 2 start
                                   as.POSIXct("2019-06-24",format="%Y-%m-%d"), #CGMP gap 3 start
                                   
                                   as.POSIXct("2019-01-01",format="%Y-%m-%d"), #SIMP gap 1 start
                                   as.POSIXct("2019-09-01",format="%Y-%m-%d"), #SIMP gap 2 start
                                   as.POSIXct("2019-08-01",format="%Y-%m-%d"), #SIMP gap 3 start
                                   
                                   as.POSIXct("2019-01-01",format="%Y-%m-%d"), #DMP gap 1 start
                                   as.POSIXct("2019-11-01",format="%Y-%m-%d"), #DMP gap 2 start
                                   
                                   as.POSIXct("2019-01-01",format="%Y-%m-%d"), #NMP gap 1 start
                                   as.POSIXct("2019-11-18",format="%Y-%m-%d"), #NMP gap 2 start
                                   
                                   as.POSIXct("2019-01-01",format="%Y-%m-%d"), #MMP gap 1 start
                                   as.POSIXct("2019-04-16",format="%Y-%m-%d"), #MMP gap 2 start
                                   
                                   as.POSIXct("2019-01-01",format="%Y-%m-%d"), #SWCMP gap 1 start
                                   as.POSIXct("2019-03-31",format="%Y-%m-%d") #SWCMP gap 2 start
                                   ),
                                    
                   "Gap_end" = c(as.POSIXct("2019-04-17",format="%Y-%m-%d"), #CGMP gap 1 end
                                   as.POSIXct("2019-12-12",format="%Y-%m-%d"), #CGMP gap 2 end
                                 as.POSIXct("2019-07-01",format="%Y-%m-%d"), #CGMP gap 3 end
                                 
                                   as.POSIXct("2019-06-11",format="%Y-%m-%d"), #SIMP gap 1 end
                                   as.POSIXct("2019-12-12",format="%Y-%m-%d"), #SIMP gap 2 end
                                 as.POSIXct("2019-08-10",format="%Y-%m-%d"), #SIMP gap 3 end
                                 
                                   as.POSIXct("2019-09-09",format="%Y-%m-%d"), #DMP gap 1 end
                                   as.POSIXct("2019-12-31",format="%Y-%m-%d"), #DMP gap 2 end
                                 
                                   as.POSIXct("2019-10-01",format="%Y-%m-%d"), #NMP gap 1 end
                                   as.POSIXct("2019-12-31",format="%Y-%m-%d"), #NMP gap 2 end
                                 
                                   as.POSIXct("2019-02-08",format="%Y-%m-%d"), #MMP gap 1 end
                                   as.POSIXct("2019-12-31",format="%Y-%m-%d"), #MMP gap 2 end
                                 
                                   as.POSIXct("2019-02-01",format="%Y-%m-%d"), #SWCMP gap 1 end
                                   as.POSIXct("2019-12-31",format="%Y-%m-%d") #SWCMP gap 2 end
                                 ),
                   
                   "npz_id" = c("Cod Grounds",
                              "Cod Grounds",
                              "Cod Grounds",
                              "Solitary Islands",
                              "Solitary Islands",
                              "Solitary Islands",
                              "Dampier",
                              "Dampier",
                              "Ningaloo",
                              "Ningaloo",
                              "Murat",
                              "Murat",
                              "South-west Corner",
                              "South-west Corner"))

# plot daily presence
ggplot() +
  geom_rect(data = hp_scene_day,
            aes(xmin = UTC, xmax = end,
                ymin = freqMin, ymax = freqMax,
                fill = bio_type)) +
  geom_rect(data = gaps,
            aes(xmin = Gap_start, xmax = Gap_end,
                ymin = min(hp_scene_day$freqMin),
                ymax = max(hp_scene_day$freqMax)),
            fill = "gray85")+
  scale_x_datetime(date_breaks = "month", date_labels = "%b")+
  facet_grid(rows = vars(npz_id)) +
  theme_bw(base_size = 14) +
  theme(axis.text.y = element_blank(), strip.text.y = element_text(face = "bold", angle = 0),
        strip.background.y = element_rect(fill = NA))

# ggsave(paste0("figs/", "HP_summary_plot_daily.png"), width=16, height=12,
#         units="in", dpi=300)


# plot weather
ggplot(data = hp_monthlight_prop) +
  geom_boxplot(aes(x = Dep_ID, y = tidal_mag_m))

```


```{r diel plot}


hp_monthlight_long <- hp_monthlight_prop |>
  pivot_longer(all_of(ends_with("_pres")), names_to = "bio_type", values_to = "presence") |>
  filter(presence > 0) |>
  mutate(var_label = case_when(
   bio_type == "bal_pres" ~ "Pygmy blue whale",
   bio_type == "hbw_pres" ~ "Humpback",
   bio_type == "fish_c_pres" ~ "Fish chorus",
   bio_type == "dol_pres" ~ "Dolphin",
   bio_type == "ves_pres" ~ "Vessel",
   bio_type == "spwh_pres" ~ "Sperm whale",
   bio_type == "mnk_pres" ~ "Minke",
   bio_type == "shr_pres" ~ "Snapping shrimp"
  ))


ggplot() +
   # geom_rect(data = hp_scene_day,
   #           aes(xmin = UTC, xmax = end,
   #              ymin = freqMin, ymax = freqMax,
   #              fill = bio_type),
   #          alpha = 0.3) +
  geom_boxplot(data = hp_monthlight_long,
            aes(x = light_reg,
                y = presence, 
                fill = light_reg)) +
    geom_point(data = hp_monthlight_long,
            aes(x = light_reg,
                y = presence, 
                color = Dep_ID),
                position = position_jitterdodge())+
  # scale_x_date(date_breaks = "1 month", date_labels = "%b")+
   scale_fill_viridis_d(begin = 0.1, end = 0.9, 
                        option = "plasma", direction = -1)+
  facet_grid(cols = vars(var_label))+
  labs(fill = "Light Regime", x = "", y = "Percent Hours Present")+
  theme_bw(base_size = 14) +
  theme(strip.text.y = element_text(face = "bold", angle = 0),
        strip.background.y = element_rect(fill = NA))


# ggsave(paste0("figs/", "HP_boxplot_diel.png"), width=16, height=12,
#         units="in", dpi=300)


```



```{r export table}

write_csv(hp_month_prop,
          "output/allsources_by_month_weather.csv")

write_csv(hp_monthlight_prop, 
          "output/allsources_by_month_diel_weather.csv")

```
