---
title: "Dissim_NMDS_cluster"
author: "Jessica McCordic"
date: "2025-09-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load libraries

```{r load lib}
library(tidyverse)
library(vegan)
library(dplyr)
library(tidyr)
library(ggplot2)
library(cluster)
library(RColorBrewer)
library(here)
library(PAMscapes)

```

## Vegan NMDS - Weekly comparisons by deployment

### Load in datasets
```{r load data}

# read in full distance matrix and metadata
dissim_og = read_csv("output/Weekly_dissim/dissim_matrix_dep_week_all.csv")

# load HMD weekly data -- has deployment ID and ISO week info
all_dep_metadata = read_csv("data/Df_analysis/All_deps_weekly_PSD.csv")

# get grouping info from original PSD data
all_dep_labels <- all_dep_metadata |>
  select(network, npz_id, Dep_ID, isoweek_UTC, effort_days) |>
  mutate(Dep_ID = str_replace(Dep_ID, "PARKSAUSTRALIA_","")) |>
  # use same filter for effort to only keep full weeks
  filter(effort_days == 7,
         # only keep MMP and SWC from Southwest network
         npz_id != "Jurien" & npz_id != "Geographe" & npz_id != "Two Rocks") |>
    # distinct combinations
  distinct() |>
  # create label that will match pivoted data to enable filtering
  mutate(dep = paste(Dep_ID, isoweek_UTC, sep = "_"))


weeks_to_use <- all_dep_labels |>
  group_by(network, isoweek_UTC) |>
  summarise(n_deps_wk = n()) |> 
  filter(n_deps_wk > 1)



dissim_all <- dissim_og |>
  left_join(all_dep_labels, by = "dep") |>
  filter(!is.na(Dep_ID)) |>
  # join with subset of weeks common to multiple deployments
  left_join(weeks_to_use) |>
  # filter out remaining weeks
  filter(!is.na(n_deps_wk)) 


```



### Filter to separate network matrices
```{r filter data}


#' --------------------------------------------------------------
#' All weeks with multiple NPZs
#' --------------------------------------------------------------

# get values of deployments left
dep_wk_all <- dissim_all$dep
# select those columns to just get dissim values we care about
dissim_all <- dissim_all |>
  select(dep, all_of(dep_wk_all))

# get rid of deployment column to make square matrix, format as distance matrix
dissim_dist_all = as.dist(dissim_all |>
                        select(-dep))


#'---------------------------------------------------------------
#' Temperate East
#'---------------------------------------------------------------


dissim_te <- dissim_all |>
  select(dep, contains("CGMP") | contains("SIMP")) |>
  filter(grepl("CGMP", dep) | grepl("SIMP", dep)) |>
  # join to get week info by deployment
  left_join(all_dep_labels, by="dep") |>
  # join with subset of weeks common to multiple deployments
  left_join(weeks_to_use) |>
  # filter out remaining weeks
  filter(!is.na(n_deps_wk)) 
# get values of deployments left
dep_wk_te <- dissim_te$dep
# select those columns to just get dissim values we care about
dissim_te <- dissim_te |>
  select(dep, all_of(dep_wk_te))


# get rid of deployment column to make square matrix, format as distance matrix
dissim_dist_te = as.dist(dissim_te |>
                        select(-dep))




#'---------------------------------------------------------------
#' North-west
#'---------------------------------------------------------------

dissim_nw <- dissim_all |>
  select(dep, contains("NINGALOO") | contains("DAMPIER")) |>
  filter(grepl("NINGALOO", dep) | grepl("DAMPIER", dep)) |>
  # join to get week info by deployment
  left_join(all_dep_labels, by="dep") |>
  # join with subset of weeks common to multiple deployments
  left_join(weeks_to_use) |>
  # filter out remaining weeks
  filter(!is.na(n_deps_wk)) 
# get values of deployments left
dep_wk_nw <- all_of(dissim_nw$dep)
# select those columns to just get dissim values we care about
dissim_nw <- dissim_nw |>
  select(dep, all_of(dep_wk_nw))


# get rid of deployment column to make square matrix, format as distance matrix
dissim_dist_nw = as.dist(dissim_nw |>
                        select(-dep))




#'---------------------------------------------------------------
#' South-west
#'---------------------------------------------------------------

dissim_sw <- dissim_all |>
  select(dep, contains("SWC") | contains("MURAT")) |>
  filter(grepl("SWC", dep) | grepl("MURAT", dep))|>
  # join to get week info by deployment
  left_join(all_dep_labels, by="dep") |>
  # join with subset of weeks common to multiple deployments
  left_join(weeks_to_use) |>
  # filter out remaining weeks
  filter(!is.na(n_deps_wk)) 
# get values of deployments left
dep_wk_sw <- all_of(dissim_sw$dep)
# select those columns to just get dissim values we care about
dissim_sw <- dissim_sw |>
  select(dep, all_of(dep_wk_sw))


# get rid of deployment column to make square matrix, format as distance matrix
dissim_dist_sw = as.dist(dissim_sw |>
                        select(-dep))
```

### NMDS all weeks

```{r NMDS all weeks}

# set start point for reproducibility
set.seed(2025) 

# calculate nmds ordination from vegan package
nmds_all <- metaMDS(dissim_dist_all, k=2, trymax = 20, autotransform = FALSE, plot = FALSE)

# get nmds scores as data frame
nmdsScores_all <- as.data.frame(scores(nmds_all)) |>
  # add deployment-months (rownames) as separate column
  rownames_to_column(var = "dep") |>
  # join to label info
  left_join(all_dep_labels) |>
  mutate(week_fac = factor(isoweek_UTC))


# explore initial patterns in ordination

ggplot(data = nmdsScores_all,
       aes(x = NMDS1, y = NMDS2)
       )+ 
  theme_bw()+
  geom_point(aes(color = npz_id,
           shape = network), 
           size = 4,
       alpha = 0.5)+
  geom_text(aes(label = week_fac,
                color = npz_id),
            vjust = -1, 
            hjust = 1.0)+
  labs(caption = "stress = 0.0405")
# 
# ggsave(paste0("figs/", "NMDS_week_all.png"), width=12, height=8,
#        units="in", dpi=300)
```



### Look into weekly presence data

```{r adding presence}

hp_week_prop <- read_csv("data/Df_analysis/prop_presence_by_week.csv") |>
  rename(isoweek_UTC = iso_week_UTC)

# want to end up with same subset of deployments/weeks included in NMDS

weekly_pres_data <- nmdsScores_all |>
  # left join with nmds to subset to common weeks and force same order
  left_join(hp_week_prop, by = c("Dep_ID", "isoweek_UTC")) |>
  # only keep data columns
  select(npz_id, network, isoweek_UTC, all_of(ends_with("_pres")))

## Evaluate correlation between ordination and environmental data
env_test <- envfit(nmds_all, 
                  weekly_pres_data, 
                  permutations = 999, 
                  na.rm = TRUE)
env_test
envScores <- as.data.frame(scores(env_test, "vectors"))

# scale vector lengths to NMDS scores rather than "unit" length
scaled_env_scores <- as.data.frame(scores(env_test, 
                            display = "vectors", 
                            arrow.mul = ordiArrowMul(env_test)))

# pull out sig scores only
sig_scaled_scores <- scaled_env_scores |>
  rownames_to_column(var = "source") |>
  filter(source == "isoweek_UTC" | source == "fish_c_pres" | source == "dol_pres")



envCent_network = as.data.frame(scores(env_test, "factors")) |>
  rownames_to_column(var = "cent_label") |>
  filter(grepl("network",cent_label))


# plot vectors onto NMDS


ggplot(data = nmdsScores_all,
       aes(x = NMDS1, y = NMDS2)
       )+ 
  theme_bw()+
  geom_point(aes(color = npz_id,
           shape = network), 
           size = 4,
       alpha = 0.5)+
  geom_text(aes(label = week_fac,
                color = npz_id),
            vjust = -1, 
            hjust = 1.0)+
  geom_segment(data =scaled_env_scores,
               aes(x=0,
                   xend=NMDS1,
                   y=0,
                   yend=NMDS2),
               arrow = arrow(length = unit(0.5, "cm")),
               colour="black",
               alpha = 0.5)+
  geom_text(data = scaled_env_scores,
            aes(x = NMDS1, 
                y = NMDS2,
                label = rownames(scaled_env_scores)),
            alpha = 0.5)+
   geom_segment(data =sig_scaled_scores,
               aes(x=0,
                   xend=NMDS1,
                   y=0,
                   yend=NMDS2),
               arrow = arrow(length = unit(0.5, "cm")),
               colour="black",
               size = 1.5)+
  geom_text(data = sig_scaled_scores,
            aes(x = NMDS1, 
                y = NMDS2,
                label = source))+
  # add network centroids from envfit
  # geom_point(data = envCent_network, 
  #            aes(x = NMDS1, y = NMDS2),
  #            size = 3)+
  # geom_text(data=envCent_network,
  #           aes(x=NMDS1,
  #               y=NMDS2,
  #               label=cent_label),
            # size=4)+
  # # add network ellipses from NMDS
  # stat_ellipse(data = nmdsScores_all,
  #              aes(group = network),
  #              linetype = "dotted",
  #              size = 1,
  #              level = 0.95)+
  # # add 
  # stat_ellipse(aes(color = npz_id),
  #              data = nmdsScores_all,
  #              size = 1,level = .95) + #95% CI ellipse (assumed multivariate normal)
  labs(caption = "stress = 0.0405 \n sig. vectors (p<0.05) in bold")
# 

ggsave(paste0("figs/", "NMDS_week_all_presence_vectors.png"), width=12, height=8,
       units="in", dpi=300)

```



# clustering

```{r cluster}
sdf_agnes = agnes(dissim_dist_all, diss = T, method = "ward")
plot(sdf_agnes)
summary(sdf_agnes)

sdf_agnes_cut <- cutree(sdf_agnes, k = 5)
nmdsScores_all$cluster = factor(sdf_agnes_cut)

# plot clusters
library(ggdendro)

# format cluster model for ggplot
dendr <- dendro_data(sdf_agnes)
dendr[["labels"]] <- merge(dendr[["labels"]], nmdsScores_all, by.x="label", by.y = "dep")


ggplot() + 
  geom_segment(data=segment(dendr), 
               aes(x=x, 
                   y=y, 
                   xend=xend,
                   yend=yend)) + 
  geom_text(data=label(dendr), 
            aes(x, y, label=label, hjust=0.5, color=cluster),
            angle = 270, size = 3)
ggsave(paste0("figs/", "AGNES_all_clusters.png"), width=12, height=12,
       units="in", dpi=300)

# plot NMDS with clusters

ggplot(data = nmdsScores_all,
       aes(x = NMDS1, y = NMDS2)
       )+ 
  theme_bw()+
  geom_point(aes(color = npz_id,
           shape = network), 
           size = 4,
       alpha = 0.5)+
  geom_text(aes(label = cluster),
            vjust = -1, 
            hjust = 1.0)+
  # geom_segment(data =envScores,
  #              aes(x=0,
  #                  xend=NMDS1,
  #                  y=0,
  #                  yend=NMDS2),
  #              arrow = arrow(length = unit(0.5, "cm")),
  #              colour="black")+
  # # add network centroids from envfit
  # geom_point(data = envCent_network, 
  #            aes(x = NMDS1, y = NMDS2),
  #            size = 3)+
  # geom_text(data=envCent_network,
  #           aes(x=NMDS1,
  #               y=NMDS2,
  #               label=cent_label),
  #           size=4)+
  # add cluster ellipses
  stat_ellipse(data = nmdsScores_all,
               aes(group = cluster),
               linetype = "dotted",
               size = 1,
               level = 0.95)+
    labs(caption = "stress = 0.0405 \n labels = clusters 1-5")

# ggsave(paste0("figs/", "NMDS_week_all_dissim_clusters.png"), width=12, height=8,
#        units="in", dpi=300)



```

```{r psd plots by cluster}

# join cluster ID to weekly PSDs

psd_week_cluster <- all_dep_metadata |>
  mutate(dep = paste0(Dep_ID, "_", isoweek_UTC),
         dep = str_replace(dep, "PARKSAUSTRALIA_","")) |>
  left_join(nmdsScores_all, 
            by = c("dep"),
            keep = FALSE) |>
  filter(!is.na(cluster))

ggplot(data = psd_week_cluster, 
       aes(x = frequency, 
           y = qmed)) +
  geom_line(aes(group = dep,
                color = isoweek_UTC.x)) +
  scale_x_log10() +
  facet_grid(cols = vars(npz_id.x),
             rows = vars(cluster))

ggsave(paste0("figs/", "PSD_by_clusters.png"), width=12, height=8,
       units="in", dpi=300)  

```


















### NMDS by network

```{r NMDS by network}


#'-----------------------------------------------
#' Temperate East NMDS
#' ---------------------------------------------

# calculate nmds ordination from vegan package
nmds_te <- metaMDS(dissim_dist_te, k=2, trymax = 20, autotransform = FALSE, plot = FALSE)

# get nmds scores as data frame
nmdsScores_te <- as.data.frame(scores(nmds_te)) |>
  # add deployment-months (rownames) as separate column
  rownames_to_column(var = "dep") |>
  # join to label info
  left_join(all_dep_labels) |>
  mutate(week_fac = factor(isoweek_UTC))


# explore initial patterns in ordination
# network 
ggplot(aes(x = NMDS1, y = NMDS2, 
           color = Dep_ID,
           shape = npz_id), 
       data = nmdsScores_te)+ 
  theme_bw()+
  geom_point(size = 3)+
  geom_text(aes(label = week_fac), 
            vjust = -1, 
            hjust = 1.0)+
  labs(caption = "stress = 0.064")

# ggsave(paste0("figs/", "NMDS_week_tempeast.png"), width=12, height=8,
#        units="in", dpi=300)



#'-----------------------------------------------
#' North-west NMDS
#' ---------------------------------------------

# calculate nmds ordination from vegan package
nmds_nw <- metaMDS(dissim_dist_nw, k=2, trymax = 20, autotransform = FALSE, plot = TRUE)

# get nmds scores as data frame
nmdsScores_nw <- as.data.frame(scores(nmds_nw)) |>
  # add deployment-months (rownames) as separate column
  rownames_to_column(var = "dep") |>
  # join to label info
  left_join(all_dep_labels) |>
  mutate(week_fac = factor(isoweek_UTC))


# explore initial patterns in ordination
# network 
ggplot(aes(x = NMDS1, y = NMDS2, 
           color = Dep_ID,
           shape = npz_id), 
       data = nmdsScores_nw)+ 
  theme_bw()+
  geom_point(size = 3)+
  geom_text(aes(label = week_fac), 
            vjust = -1, 
            hjust = 1.0) +
  labs(caption = "stress = 0.217 (may have insufficient data)")

# ggsave(paste0("figs/", "NMDS_week_northwest.png"), width=12, height=8,
#        units="in", dpi=300)



#'-----------------------------------------------
#' South-west NMDS
#' ---------------------------------------------

# calculate nmds ordination from vegan package
nmds_sw <- metaMDS(dissim_dist_sw, k=2, trymax = 20, autotransform = FALSE, plot = FALSE)

# get nmds scores as data frame
nmdsScores_sw <- as.data.frame(scores(nmds_sw)) |>
  # add deployment-months (rownames) as separate column
  rownames_to_column(var = "dep") |>
  # join to label info
  left_join(all_dep_labels) |>
  mutate(week_fac = factor(isoweek_UTC))


# explore initial patterns in ordination
# network 
ggplot(aes(x = NMDS1, y = NMDS2, 
           color = Dep_ID,
           shape = npz_id), 
       data = nmdsScores_sw)+ 
  theme_bw()+
  geom_point(size = 3)+
  geom_text(aes(label = week_fac), 
            vjust = -1, 
            hjust = 1.0) +
  labs(caption = "stress = 0.0024")

# ggsave(paste0("figs/", "NMDS_week_southwest.png"), width=12, height=8,
#        units="in", dpi=300)


```