---
title: "Dissim_NMDS_cluster"
author: "Jessica McCordic"
date: "2025-09-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load libraries

```{r load lib}
library(tidyverse)
library(vegan)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggdendro)
library(cluster)
library(fpc)
library(RColorBrewer)
library(here)
library(PAMscapes)

```

## Vegan NMDS - Weekly comparisons by deployment

### Load in datasets
```{r load data}

# read in full distance matrix and metadata
dissim_og <- read_csv("data/Df_analysis/Dissim_tables/dissim_matrix_dep_month_diel.csv")

# load HMD weekly data -- has deployment ID and ISO week info
all_dep_psd <- read_csv("data/Df_analysis/All_deps_monthly_diel_PSD.csv")

# get grouping info from original PSD data
all_dep_labels <- all_dep_psd |>
  select(network, npz_id, Dep_ID, month_UTC,light_reg) |>
  mutate(Dep_ID = str_replace(Dep_ID, "PARKSAUSTRALIA_","")) |>
  filter(# only keep MMP and SWC from Southwest network
         npz_id != "Jurien" & npz_id != "Geographe" & npz_id != "Two Rocks") |>
    # distinct combinations
  distinct() |>
  # create label that will match pivoted data to enable filtering
  mutate(dep = paste(Dep_ID, month_UTC, light_reg, sep = "_"))



dissim_all <- dissim_og |>
  left_join(all_dep_labels, by = "dep") |>
  filter(!is.na(Dep_ID))


```



### Format dissimilarity matrix
```{r filter data}


#' --------------------------------------------------------------
#' All NPZs
#' --------------------------------------------------------------

# get values of deployments to use
dep_light_all <- dissim_all$dep
# select those columns to just get dissim values we care about
dissim_all <- dissim_all |>
  select(dep, all_of(dep_light_all))

# get rid of deployment column to make square matrix, format as distance matrix
dissim_dist_all = as.dist(dissim_all |>
                        select(-dep))


#'---------------------------------------------------------------
#' Temperate East
#'---------------------------------------------------------------


dissim_te <- dissim_all |>
  select(dep, contains("CGMP") | contains("SIMP")) |>
  filter(grepl("CGMP", dep) | grepl("SIMP", dep)) |>
  # join to get info by deployment
  left_join(all_dep_labels, by="dep")
 
# get values of deployments left
dep_wk_te <- dissim_te$dep
# select those columns to just get dissim values we care about
dissim_te <- dissim_te |>
  select(dep, all_of(dep_wk_te))


# get rid of deployment column to make square matrix, format as distance matrix
dissim_dist_te = as.dist(dissim_te |>
                        select(-dep))

```

## All NPZs
### NMDS 

```{r NMDS}

# set start point for reproducibility
set.seed(2025) 

# calculate nmds ordination from vegan package
nmds_all <- metaMDS(dissim_dist_all, k=2,  autotransform = FALSE, plot = FALSE)

nmds_stress <- nmds_all$stress

# get nmds scores as data frame
nmdsScores_all <- as.data.frame(scores(nmds_all)) |>
  # add deployment-months (rownames) as separate column
  rownames_to_column(var = "dep") |>
  # join to label info
  left_join(all_dep_labels) |>
  mutate(month_fac = factor(month_UTC),
         light_fac = factor(light_reg))


# explore initial patterns in ordination

ggplot(data = nmdsScores_all,
       aes(x = NMDS1, y = NMDS2)
       )+ 
  theme_bw()+
  geom_point(aes(color = npz_id,
    shape = light_fac), 
           size = 4,
       alpha = 0.5)+
   stat_ellipse(aes(group = npz_id,
                    color = npz_id),
               data = nmdsScores_all,
               size = 1,level = .95) + #95% CI ellipse (assumed multivariate normal)
  geom_text(aes(label = month_UTC,
                color = npz_id),
            vjust = -1,
            hjust = 1.0)+
  labs(caption = paste0("stress = ", nmds_all$stress))
# 
# ggsave(paste0("figs/", "NMDS_month_diel_all_npz_color.png"), width=12, height=8,
#        units="in", dpi=300)
```



### Look into presence data

```{r load and summarize presence}

hp_month_prop <- read_csv("data/All_sites_tables/allsources_by_month_diel_weather.csv") 

# quick fn to calculate min-max normalized values for weather data

minmax_norm <- function(x, NAbehav = TRUE){
    
  scaled_val <- (x - min(x, na.rm = NAbehav))/(max(x, na.rm = NAbehav) - min(x, na.rm = NAbehav))
  return(scaled_val)
}


# add month-diel pres to NMDS scores
monthly_pres_data <- nmdsScores_all |>
  # left join with nmds to subset to common weeks and force same order
  left_join(hp_month_prop, by = c("Dep_ID", "month_UTC", "light_reg")) |>
  mutate(month_fac = as_factor(month_UTC),
           tide_sc = minmax_norm(tidal_mag_m),
           rain_sc = minmax_norm(rain_month_avg_mm),
           wind_am_sc = minmax_norm(wind_am_month_avg_kmh),
           wind_pm_sc = minmax_norm(wind_pm_month_avg_kmh),
           wind_hourly_sc = minmax_norm(mean_wind_km_h)) |>
  rowwise() |>
  mutate(wind_ampm_avg_sc = mean(c(wind_am_sc, wind_pm_sc))
  )


ggplot(data = monthly_pres_data, 
       aes(x = npz_id, 
           y = fish_c_pres,
           fill = light_fac)) +
  geom_boxplot()





```


```{r Presence correlation with NMDS}

  ## Evaluate correlation between ordination and environmental data
  env_test <- envfit(nmds_all, 
                     monthly_pres_data |>
                       # keep grouping columns, weather, and presence columns
                       select(npz_id, network, light_reg, 
                              all_of(ends_with("_pres")),
                              tide_sc, rain_sc, wind_ampm_avg_sc), 
                     permutations = 999, 
                     na.rm = TRUE)
env_test


env_pvals_vec <- env_test$vectors$pvals |>
  enframe()
env_output_vec <- env_test$vectors$r |>
  enframe()|>
  rename("r2" = "value")|>
  left_join(env_pvals_vec) |>
  arrange(desc(r2))



env_pvals_fac <- env_test$factors$pvals |>
  enframe()
env_output_fac <- env_test$factors$r |>
  enframe() |>
  rename("r2" = "value")|>
  left_join(env_pvals_fac)|>
  arrange(desc(r2))

env_output_all <- env_output_fac |>
  rbind(env_output_vec)

write_csv(env_output_all, "output/envfit_output.csv")



envScores <- as_tibble(scores(env_test, "vectors"), rownames = "name") |>
  left_join(env_pvals_vec) |>
  rename("Variable" = "name", 
         "pval" = "value")|>
  mutate(var_label = case_when(
   Variable == "month_UTC" ~ "Month",
   Variable == "rain_sc" ~ "Rainfall",
   Variable == "tide_sc" ~ "Tidal magnitude",
   Variable == "wind_ampm_avg_sc" ~ "Wind speed",
   Variable == "bal_pres" ~ "Pygmy blue whale",
   Variable == "hbw_pres" ~ "Humpback",
   Variable == "fish_c_pres" ~ "Fish chorus",
   Variable == "dol_pres" ~ "Dolphin",
   Variable == "ves_pres" ~ "Vessel",
   Variable == "spwh_pres" ~ "Sperm whale",
   Variable == "mnk_pres" ~ "Minke",
   Variable == "shr_pres" ~ "Snapping shrimp"
  ))


# scale vector lengths to NMDS scores rather than "unit" length
# have to use base plots to get scaling to work
plot(nmds_all)
plot(env_test)

scaled_env_scores <- as.data.frame(scores(env_test, 
                                          display = "vectors",
                                          arrow.mul = ordiArrowMul(env_test))) |>
  as_tibble(rownames = "name") |>
  left_join(env_pvals_vec) |>
  rename("Variable" = "name", 
         "pval" = "value")|>
  mutate(var_label = case_when(
   Variable == "month_UTC" ~ "Month",
   Variable == "rain_sc" ~ "Rainfall",
   Variable == "tide_sc" ~ "Tidal magnitude",
   Variable == "wind_ampm_avg_sc" ~ "Wind speed",
   Variable == "bal_pres" ~ "Pygmy blue whale",
   Variable == "hbw_pres" ~ "Humpback",
   Variable == "fish_c_pres" ~ "Fish chorus",
   Variable == "dol_pres" ~ "Dolphin",
   Variable == "ves_pres" ~ "Vessel",
   Variable == "spwh_pres" ~ "Sperm whale",
   Variable == "mnk_pres" ~ "Minke",
   Variable == "shr_pres" ~ "Snapping shrimp"
  ))

# pull out sig scores only
sig_scaled_scores <- scaled_env_scores |>
  filter(pval <= 0.05)

envCent_network = as.data.frame(scores(env_test, 
                                       display = "factors",
                            arrow.mul = ordiArrowMul(env_test))) |>
  rownames_to_column(var = "cent_label") |>
  filter(grepl("network",cent_label))

envCent_npz = as.data.frame(scores(env_test, , 
                                       display = "factors",
                            arrow.mul = ordiArrowMul(env_test))) |>
  rownames_to_column(var = "cent_label") |>
  filter(grepl("npz_id",cent_label)) |>
  mutate(cent_label = str_replace(cent_label, "npz_id", ""))

# plot vectors onto NMDS


ggplot(data = nmdsScores_all,
       aes(x = NMDS1, y = NMDS2)
       )+ 
  theme_bw()+
  geom_point(aes(color = npz_id,
           shape = network), 
           size = 4,
       alpha = 0.5)+
   geom_segment(data =sig_scaled_scores,
               aes(x=0,
                   xend=NMDS1,
                   y=0,
                   yend=NMDS2),
               arrow = arrow(length = unit(0.5, "cm")),
               colour="grey50",
               size = 1)+
  geom_text(data = sig_scaled_scores,
            aes(x = NMDS1,
                y = NMDS2,
                label = Variable))+
  # add network centroids from envfit
  geom_point(data = envCent_network,
             aes(x = NMDS1, y = NMDS2),
             size = 3)+
  # geom_text(data=envCent_network,
  #           aes(x=NMDS1,
  #               y=NMDS2,
  #               label=cent_label),
  # size=4)+
  geom_point(data = envCent_npz,
             aes(x = NMDS1, y = NMDS2),
             color = "grey80",
             size = 3)+
  geom_text(data=envCent_npz,
            aes(x=NMDS1,
                y=NMDS2,
                label=cent_label),
  size=4)+
  # add network ellipses from NMDS
  # stat_ellipse(aes(group = network),
  #              data = nmdsScores_all,
  #              size = 1,level = .95) + #95% CI ellipse (assumed multivariate normal)
  #  stat_ellipse(aes(group = npz_id),
  #              data = nmdsScores_all,
  #              linetype = "dotted",
  #              size = 1,level = .95) +
  labs(caption = paste0("Stress = ", round(nmds_stress, digits = 4), "\n Arrows indicate sig. vectors (p<0.05)"))
# 
# 
# ggsave(paste0("figs/", "NMDS_month_diel_sig_vectors.png"), width=12, height=8,
#        units="in", dpi=300)

```

# clustering

```{r cluster}
sdf_agnes = agnes(dissim_dist_all, diss = T, method = "ward")

# Visually assess the tree
plot(sdf_agnes,which.plots = 2)
summary(sdf_agnes)

# k = 5 seems reasonable based on looking at dendrogram
# use clusterboot() from fpc package to test stability of clusters if k=5

agnes_boot <- clusterboot(dissim_dist_all, 
            clustermethod = hclustCBI, 
            method = "ward.D2",
            k = 5,
            seed = 32165)

# From "Practical Data Science With R" book, Ch 8:
# "As a rule of thumb, clusters with a
# stability value less than 0.6 should be considered unstable. Values between 0.6 and 0.75
# indicate that the cluster is measuring a pattern in the data, but there isn’t high certainty about which points should be clustered together. Clusters with stability values
# above about 0.85 can be considered highly stable (they’re likely to be real clusters)."
agnes_boot$bootmean
# [1] 0.7291170 0.6791824 0.9870130 0.9371382 0.7320519
agnes_boot$bootbrd
# [1] 20 34  1  2 30

# Suggests cluster 1 (CGMP), 2 (DMP), and 5 (SIMP) are less stable than 3 (MMP) and 4 (SWCMP/NMP)
# -- all are still above 'rule of thumb' 0.6 cutoff



sdf_agnes_cut <- cutree(sdf_agnes, k = 5)
nmdsScores_all$cluster = factor(sdf_agnes_cut)

# format cluster model for ggplot
dendr <- dendro_data(sdf_agnes)
dendr[["labels"]] <- merge(dendr[["labels"]], nmdsScores_all, by.x="label", by.y = "dep")

```

### PERMANOVA tests

```{r permanova}

# Test assumption that dispersion is similar among groups
#  --> NS result means we can proceed with PERMANOVA
disp_cluster <- betadisper(dissim_dist_all, 
                           group = nmdsScores_all$cluster)

plot(disp_cluster)

anova(disp_cluster)

# Response: Distances
#           Df     Sum Sq    Mean Sq F value Pr(>F)
# Groups     4 0.00012096 3.0239e-05  1.1266 0.3542
# Residuals 52 0.00139579 2.6842e-05 

#### PERMANOVA test for whether clusters are significantly different from one another

perma_cluster <- adonis2(dissim_dist_all~as.factor(nmdsScores_all$cluster), data = dissim_dist_all, permutations = 9999)

perma_cluster

# adonis2(formula = dissim_dist_all ~ as.factor(nmdsScores_all$cluster), data = dissim_dist_all, permutations = 9999)
#          Df SumOfSqs      R2      F Pr(>F)    
# Model     4 0.029566 0.85908 79.252  1e-04 ***
# Residual 52 0.004850 0.14092                  
# Total    56 0.034416 1.00000                  
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

```






### Plots for all NPZs


```{r plot dendrogram}
# plot dendrogram
ggplot() + 
  geom_segment(data=segment(dendr), 
               aes(x=x, 
                   y=y, 
                   xend=xend,
                   yend=yend)) + 
  geom_text(data=ggdendro::label(dendr), 
            aes(x, y, label=label, hjust=1, color=cluster),
            angle = 90, size = 3)+
  expand_limits(y = c(-0.10, 0.22))+
  scale_color_viridis_d(begin = 0.1, end = 0.8)
# ggsave(paste0("figs/", "AGNES_all_month_diel_clusters_k5.png"), width=12, height=12,
#        units="in", dpi=300)
```


``` {r plot NMDS clusters}
# plot NMDS with clusters


hull_clust <- nmdsScores_all |>
  group_by(cluster) |>
  slice(chull(NMDS1, NMDS2))


ggplot(data = nmdsScores_all,
       aes(x = NMDS1, y = NMDS2)
       )+ 
  theme_bw()+
   # add cluster ellipses
  stat_ellipse(data = nmdsScores_all,
               aes(color = cluster,
                   fill = cluster),
               geom = "polygon",
               size = 1,
               alpha = 0.2)+
  # add vectors for sig continuous variables
  geom_segment(data =sig_scaled_scores,
               aes(x=0,
                   xend=NMDS1,
                   y=0,
                   yend=NMDS2),
               arrow = arrow(angle = 30, 
                             length = unit(0.25, "cm"),
                             type = "open"),
               colour = "grey45",
               size = 1)+
  geom_point(data = nmdsScores_all, 
             aes(color = cluster,
           shape = network), 
           # alpha = 0.7,
           size = 3) +
  # geom_polygon(data = hull_clust,
  #              aes(x = NMDS1, y = NMDS2,
  #                  fill = cluster,
  #                  color = cluster),
  #              linewidth = 0.25,
  #              alpha = 0.2)+
  
  geom_text(data = sig_scaled_scores,
            aes(x = NMDS1,
                y = NMDS2,
                label = var_label),
            color = "grey45",
            fontface = "bold",
            vjust = -0.5, hjust = 0.5)+
 # add npz centroids from envfit
  # geom_point(data = envCent_npz,
  #            aes(x = NMDS1, y = NMDS2),
  #            shape = 21,
  #            size = 3)+
  # geom_text(data=envCent_npz,
  #           aes(x=NMDS1,
  #               y=NMDS2,
  #               label=cent_label),
  #           size=4)+
  scale_color_viridis_d(begin = 0.1, end = 0.8)+
  scale_fill_viridis_d(begin = 0.1, end = 0.8)+
    labs(caption = paste0("stress = ", round(nmds_all$stress, digits =4)),
         fill = "Cluster", shape = "Network")+
  guides(color = "none")+
  theme_bw(base_size = 14)

# ggsave(paste0("figs/", "NMDS_month_diel_all_clust_ellipse.png"), width=8, height=6,
#        units="in", dpi=300)



```

```{r plot PSDs by cluster}

# join cluster ID to weekly PSDs

psd_monthdiel_cluster <- all_dep_psd |>
  mutate(dep = paste0(Dep_ID, "_", month_UTC,"_",light_reg),
         dep = str_replace(dep, "PARKSAUSTRALIA_","")) |>
  left_join(nmdsScores_all, 
            by = c("dep"),
            keep = FALSE) |>
  filter(!is.na(cluster))

# make summarized df for plotting by cluster & light regime
psd_clust_light <- psd_monthdiel_cluster |>
  group_by(cluster, light_fac, frequency) |>
   summarize(
    min_psd = min(qmed),
    med_psd = median(qmed),
    max_psd = max(qmed)
  )

# make summarized df for plotting by cluster only
psd_clust <- psd_monthdiel_cluster |>
  group_by(dep) |>
  mutate(norm_qmed = qmed/sum(qmed))|>
  ungroup() |>
  group_by(cluster, frequency) |>
   summarize(
    min_psd = min(qmed),
    med_psd = median(qmed),
    max_psd = max(qmed),
    norm_min_psd = min(norm_qmed),
    norm_med_psd = median(norm_qmed),
    norm_max_psd = max(norm_qmed)
    
  ) |>
  # add labeling column
  mutate(clust_label = case_when(
    cluster == 1 ~ "Cod Grounds",
    cluster == 2 ~ "Dampier",
    cluster == 3 ~ "Murat",
    cluster == 4 ~ "Ningaloo & \nSouth-west Corner",
    cluster == 5 ~ "Solitary Islands"
  ))

# plot median PSDs for each month x light, facet by cluster
ggplot(data = psd_clust, 
       aes(x = frequency)) +
  geom_ribbon(aes(ymin = min_psd,
                  ymax = max_psd,
                  group = cluster,
                  fill = cluster),
              alpha = 0.2)+
  geom_line(aes(y = med_psd,
                group = cluster,
                color = cluster),
            linewidth = 0.7) +
    geom_line(aes(y = min_psd,
                group = cluster,
                color = cluster),
              alpha = 0.5,
            linewidth = 0.25) +
    geom_line(aes(y = max_psd,
                group = cluster,
                color = cluster),
              alpha = 0.5,
            linewidth = 0.25) +
  geom_line(data = psd_monthdiel_cluster,
            aes(x = frequency,
                y = qmed,
                group = interaction(cluster,dep),
                color = cluster),
            alpha = 0.4,
            linewidth = 0.5)+
  labs(x = "Frequency", 
       y = expression(paste("dB re 1", mu, "Pa"^"2", "Hz"^"-1")),
       color = "Cluster",
       fill = "Cluster")+
  scale_x_log10() +
  scale_fill_viridis_d(begin = 0.1, end = 0.8)+
  scale_color_viridis_d(begin = 0.1, end = 0.8)+
  facet_grid(rows = vars(cluster))+
  theme_bw(base_size = 14) +
  theme(strip.text.y = element_text(face = "bold", angle = 0),
        strip.background.y = element_rect(fill = NA))



# ggsave(paste0("figs/", "PSD_by_clusters_shading_lines.png"), width=7, height=12,
#        units="in", dpi=300)


psd_clust_labels <- psd_clust |> 
  filter(frequency == 23961) |>
  mutate(med_psd_labels = case_when(
    clust_label == "Cod Grounds" ~ med_psd - 0.5,
    clust_label == "Dampier" ~ med_psd + 0.5,
    TRUE ~ med_psd
  ),
  norm_med_psd_labels = case_when(
    clust_label == "Cod Grounds" ~ norm_med_psd - 0.000005,
    clust_label == "Dampier" ~ norm_med_psd + 0.000005,
    TRUE ~ norm_med_psd))


# plot normalized summary PSDs by cluster in single plot
ggplot(data = psd_clust, 
       aes(x = frequency)) +
  geom_line(aes(y = norm_med_psd,
                group = cluster,
                color = cluster),
            linewidth = 1) +
  geom_label(data = psd_clust_labels,
            aes(y = norm_med_psd_labels,
                label = clust_label,
                hjust = -0.05,
            color = cluster))+
  labs(x = "Frequency", 
       y = "Normalized PSD",
       color = "Cluster",
       fill = "Cluster")+
  scale_x_log10() +
  expand_limits(x = c(10, 50000))+
  scale_fill_viridis_d(begin = 0.1, end = 0.8)+
  scale_color_viridis_d(begin = 0.1, end = 0.8)+
  theme_bw(base_size = 14) +
  theme(strip.text.y = element_text(face = "bold", angle = 0),
        strip.background.y = element_rect(fill = NA))

# ggsave(paste0("figs/", "norm_PSD_by_clusters_medlines.png"), width=14, height=8,
#        units="in", dpi=300)


```



## Temperate East only

### NMDS Temp East

```{r NMDS TE}


#'-----------------------------------------------
#' Temperate East NMDS
#' ---------------------------------------------

# calculate nmds ordination from vegan package
nmds_te <- metaMDS(dissim_dist_te, k=2, trymax = 20, autotransform = FALSE, plot = FALSE)

# get nmds scores as data frame
nmdsScores_te <- as.data.frame(scores(nmds_te)) |>
  # add deployment-months (rownames) as separate column
  rownames_to_column(var = "dep") |>
  # join to label info
  left_join(all_dep_labels) |>
  mutate(month_fac = factor(month_UTC),
         light_fac = factor(light_reg))


# explore initial patterns in ordination
 
ggplot(aes(x = NMDS1, y = NMDS2,
           color = npz_id,
           shape = light_reg),
       data = nmdsScores_te)+
  theme_bw()+
  geom_point(size = 3)+
  # geom_text(aes(label = week_fac),
  #           vjust = -1,
  #           hjust = 1.0)+
  labs(caption = paste0("stress = ", round(nmds_te$stress, digits =4)))

# ggsave(paste0("figs/", "NMDS_month_diel_tempeast.png"), width=12, height=8,
#        units="in", dpi=300)


```


### Adding presence for Temp East
```{r temp east presence}

# add monthly pres to NMDS scores
monthly_pres_te <- nmdsScores_te |>
  # left join with nmds to subset to common weeks and force same order
  left_join(hp_month_prop, by = c("Dep_ID", "month_UTC", "light_reg")) |>
  mutate(month_fac = as_factor(month_UTC),
         light_reg = as_factor(light_reg)) |>
  select(-c(spwh_pres)) |>
  rowwise() |>
  mutate(wind_ampm_avg_month = mean(wind_am_month_avg_kmh:wind_pm_month_avg_kmh))
  

  ## Evaluate correlation between ordination and environmental data
  env_test_te <- envfit(nmds_te, 
                     monthly_pres_te|>
                       # only keep grouping columns and presence columns
                         select(npz_id, light_reg, month_UTC,  
                              rain_month_avg_mm,
                              all_of(ends_with("_pres"))),
                     permutations = 999, 
                     na.rm = TRUE)
env_test_te




```



### Clustering Temp East

```{r cluster Temp East}
sdf_agnes_te = agnes(dissim_dist_te, diss = T, method = "ward")
plot(sdf_agnes_te, which.plots = 2)
summary(sdf_agnes_te)


# use clusterboot() from fpc package to test stability of clusters if k=5

agnes_boot_te <- clusterboot(dissim_dist_te, 
            clustermethod = hclustCBI, 
            method = "ward.D2",
            k = 4,
            seed = 32165)

agnes_boot_te$bootmean
agnes_boot_te$bootbrd

sdf_agnes_te_cut <- cutree(sdf_agnes_te, k = 4)
nmdsScores_te$cluster = factor(sdf_agnes_te_cut)

# plot clusters
library(ggdendro)

# format cluster model for ggplot
dendr_te <- dendro_data(sdf_agnes_te)
dendr_te[["labels"]] <- merge(dendr_te[["labels"]], nmdsScores_te, by.x="label", by.y = "dep")


ggplot() + 
  geom_segment(data=segment(dendr_te), 
               aes(x=x, 
                   y=y, 
                   xend=xend,
                   yend=yend)) + 
  geom_text(data=ggdendro::label(dendr_te), 
            aes(x, y, label=label, hjust=0.5, color=cluster),
            angle = 90, size = 3)

ggsave(paste0("figs/", "AGNES_tempeast_month_diel_clusters_k4.png"), width=12, height=12,
       units="in", dpi=300)


```


### PERMANOVA tests Temp East

```{r permanova temp east}

# Test assumption that dispersion is similar among groups
#  --> NS result means we can proceed with PERMANOVA
disp_cluster_te <- betadisper(dissim_dist_te, 
                           group = nmdsScores_te$cluster)

plot(disp_cluster_te)

anova(disp_cluster_te)
 
# Response: Distances
#           Df     Sum Sq    Mean Sq F value Pr(>F)
# Groups     3 3.1362e-05 1.0454e-05  0.8886 0.4601
# Residuals 26 3.0589e-04 1.1765e-05   

#### PERMANOVA test for whether clusters are significantly different from one another

perma_cluster_te <- adonis2(dissim_dist_te~as.factor(nmdsScores_te$cluster), data = dissim_dist_te, permutations = 9999)

perma_cluster_te

# adonis2(formula = dissim_dist_te ~ as.factor(nmdsScores_te$cluster), data = dissim_dist_te, permutations = 9999)
#          Df  SumOfSqs      R2      F Pr(>F)    
# Model     3 0.0029639 0.73322 23.819  1e-04 ***
# Residual 26 0.0010784 0.26678                  
# Total    29 0.0040423 1.00000   

```


### Plots for Temp East

```{r TE NMDS plots}


# plot NMDS w/clusters


env_pvals_vec_te <- env_test_te$vectors$pvals |>
  enframe()

env_pvals_fac_te <- env_test_te$factors$pvals |>
  enframe()


envScores_te <- as_tibble(scores(env_test_te, "vectors"), rownames = "name") |>
  left_join(env_pvals_vec_te) |>
  rename("Variable" = "name", 
         "pval" = "value") |>
  mutate(var_label = case_when(
   Variable == "month_UTC" ~ "Month",
   Variable == "rain_month_avg_mm" ~ "Rainfall",
   Variable == "bal_pres" ~ "Pygmy blue whale",
   Variable == "hbw_pres" ~ "Humpback",
   Variable == "fish_c_pres" ~ "Fish chorus",
   Variable == "dol_pres" ~ "Dolphin",
   Variable == "ves_pres" ~ "Vessel",
   Variable == "mnk_pres" ~ "Minke",
   Variable == "shr_pres" ~ "Snapping shrimp"
  ))


# scale vector lengths to NMDS scores rather than "unit" length
# have to use base plots to get scaling to work
plot(nmds_te)
plot(env_test_te)

scaled_env_scores_te <- as.data.frame(scores(env_test_te, 
                                          display = "vectors",
                                          arrow.mul = ordiArrowMul(env_test_te))) |>
  as_tibble(rownames = "name") |>
  left_join(env_pvals_vec_te) |>
  rename("Variable" = "name", 
         "pval" = "value")|>
  mutate(var_label = case_when(
   Variable == "month_UTC" ~ "Month",
   Variable == "rain_month_avg_mm" ~ "Rainfall",
   Variable == "bal_pres" ~ "Pygmy blue whale",
   Variable == "hbw_pres" ~ "Humpback",
   Variable == "fish_c_pres" ~ "Fish chorus",
   Variable == "dol_pres" ~ "Dolphin",
   Variable == "ves_pres" ~ "Vessel",
   Variable == "mnk_pres" ~ "Minke",
   Variable == "shr_pres" ~ "Snapping shrimp"
  ))

# pull out sig scores only
sig_scaled_scores_te <- scaled_env_scores_te |>
  filter(pval <= 0.05)

envCent_npz_te = as.data.frame(scores(env_test_te,
                                       display = "factors",
                            arrow.mul = ordiArrowMul(env_test_te))) |>
  rownames_to_column(var = "cent_label") |>
  filter(grepl("npz_id",cent_label)) |>
  mutate(cent_label = str_replace(cent_label, "npz_id", ""))






# get convex hull polygon for each cluster

hull_te <- nmdsScores_te |>
  group_by(cluster) |>
  slice(chull(NMDS1, NMDS2))


ggplot(data = nmdsScores_te,
       aes(x = NMDS1, y = NMDS2)
)+ 
  theme_bw()+
  stat_ellipse(aes(fill = cluster,
                   color = cluster),
               geom = "polygon",
               alpha = 0.2)+
  # use convex hull for cluster 4 since you need >3 points for an ellipse
  geom_polygon(data = hull_te |> filter(cluster == 4),
               aes(x = NMDS1, y = NMDS2,
                   fill = cluster,
                   color = cluster),
               linewidth = 0.25,
               alpha = 0.2)+
  geom_point(data = nmdsScores_te, 
             aes(color = cluster,
                 shape = npz_id), 
             size = 4) +
  geom_segment(data =sig_scaled_scores_te,
               aes(x=0,
                   xend=NMDS1,
                   y=0,
                   yend=NMDS2),
               arrow = arrow(angle = 30, 
                             length = unit(0.25, "cm"),
                             type = "open"),
               colour = "grey45",
               size = 1)+
  geom_text(data = sig_scaled_scores_te,
            aes(x = NMDS1,
                y = NMDS2,
                label = var_label),
            color = "grey45",
            fontface = "bold")+
  scale_color_viridis_d(begin = 0.3, end = 0.8, option = "plasma")+
      scale_fill_viridis_d(begin = 0.3, end = 0.8, option = "plasma")+
    labs(caption = paste0("stress = ", round(nmds_te$stress, digits =4)), 
         fill = "Cluster", 
         shape = "NPZ") +
  guides(color = "none")+
  theme_bw(base_size = 14)

# ggsave(paste0("figs/", "NMDS_month_diel_tempeast_clust_vec.png"), width=8, height=6,
#        units="in", dpi=300)





```


```{r TE PSD plots}


# join cluster ID to weekly PSDs

psd_monthdiel_cluster_te <- all_dep_psd |>
  mutate(dep = paste0(Dep_ID, "_", month_UTC,"_",light_reg),
         dep = str_replace(dep, "PARKSAUSTRALIA_","")) |>
  left_join(nmdsScores_te, 
            by = c("dep"),
            keep = FALSE) |>
  filter(!is.na(cluster))

# make summarized df for plotting by cluster & light regime
psd_clust_light_te <- psd_monthdiel_cluster_te |>
  group_by(cluster, light_fac, frequency) |>
   summarize(
    min_psd = min(qmed),
    med_psd = median(qmed),
    max_psd = max(qmed)
  )

# make summarized df for plotting by cluster only
psd_clust_te <- psd_monthdiel_cluster_te |>
  group_by(dep) |>
  mutate(norm_qmed = qmed/sum(qmed))|>
  ungroup() |>
  group_by(cluster, frequency) |>
   summarize(
    min_psd = min(qmed),
    med_psd = median(qmed),
    max_psd = max(qmed),
    norm_min_psd = min(norm_qmed),
    norm_med_psd = median(norm_qmed),
    norm_max_psd = max(norm_qmed)
    
  ) |>
  # add labeling column
  mutate(clust_label = case_when(
    cluster == 1 ~ "Cod Grounds \nall others",
    cluster == 2 ~ "Cod Grounds \nJune+July(night)",
    cluster == 3 ~ "Solitary Islands \nJun - Aug",
    cluster == 4 ~ "Solitary Islands \nDec"
  ))

# plot median PSDs for each month x light, facet by cluster
ggplot(data = psd_clust_te, 
       aes(x = frequency)) +
  geom_ribbon(aes(ymin = min_psd,
                  ymax = max_psd,
                  group = cluster,
                  fill = cluster),
              alpha = 0.2)+
  geom_line(aes(y = med_psd,
                group = cluster,
                color = cluster),
            linewidth = 0.7) +
    geom_line(aes(y = min_psd,
                group = cluster,
                color = cluster),
              alpha = 0.5,
            linewidth = 0.25) +
    geom_line(aes(y = max_psd,
                group = cluster,
                color = cluster),
              alpha = 0.5,
            linewidth = 0.25) +
  geom_line(data = psd_monthdiel_cluster_te,
            aes(x = frequency,
                y = qmed,
                group = interaction(cluster,dep),
                color = cluster),
            alpha = 0.4,
            linewidth = 0.5)+
  labs(x = "Frequency", 
       y = expression(paste("dB re 1", mu, "Pa"^"2", "Hz"^"-1")),
       color = "Cluster",
       fill = "Cluster")+
  scale_x_log10() +
  scale_fill_viridis_d(begin = 0.1, end = 0.8, option = "plasma")+
  scale_color_viridis_d(begin = 0.1, end = 0.8, option = "plasma")+
  facet_grid(rows = vars(cluster))+
  theme_bw(base_size = 14) +
  theme(strip.text.y = element_text(face = "bold", angle = 0),
        strip.background.y = element_rect(fill = NA))


# 
# ggsave(paste0("figs/", "PSD_by_clusters_shading_lines_tempeast.png"), width=7, height=12,
#        units="in", dpi=300)


psd_clust_labels_te <- psd_clust_te |> 
  filter(frequency == 23961) |>
  mutate(
  norm_med_psd_labels = case_when(
   cluster == 1 ~ norm_med_psd + 0.0000075,
   cluster == 2 ~ norm_med_psd - 0.000010,
   cluster == 3 ~ norm_med_psd - 0.000005,
   cluster == 4 ~ norm_med_psd + 0.000010))


# plot normalized summary PSDs by cluster in single plot
ggplot(data = psd_clust_te, 
       aes(x = frequency)) +
  geom_line(aes(y = norm_med_psd,
                group = cluster,
                color = cluster),
            linewidth = 1) +
  geom_label(data = psd_clust_labels_te,
            aes(y = norm_med_psd_labels,
                label = clust_label,
                hjust = -0.05,
            color = cluster))+
  labs(x = "Frequency", 
       y = "Normalized PSD",
       color = "Cluster",
       fill = "Cluster")+
  scale_x_log10() +
  expand_limits(x = c(10, 50000))+
  scale_fill_viridis_d(begin = 0.1, end = 0.8, option = "plasma")+
  scale_color_viridis_d(begin = 0.1, end = 0.8, option = "plasma")+
  theme_bw(base_size = 14) +
  theme(strip.text.y = element_text(face = "bold", angle = 0),
        strip.background.y = element_rect(fill = NA))

# ggsave(paste0("figs/", "norm_PSD_by_clusters_medlines_tempeast.png"), width=14, height=8,
#        units="in", dpi=300)


```




